name: flutter_intercom
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Apple icons
  cupertino_icons: ^0.1.3

  #To access device shared prefrences
  shared_preferences: ^0.5.8

  #Firebase
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
  firebase_auth: ^0.18.0
  firebase: ^7.3.0

  #Google authentication
  google_sign_in_all: ^0.0.3

  #Loading
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

